// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: linter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_FORMAT_UNKNOWN Format = 0
	Format_FORMAT_JSON    Format = 1
	Format_FORMAT_YAML    Format = 2
	Format_FORMAT_TOML    Format = 3
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_UNKNOWN",
		1: "FORMAT_JSON",
		2: "FORMAT_YAML",
		3: "FORMAT_TOML",
	}
	Format_value = map[string]int32{
		"FORMAT_UNKNOWN": 0,
		"FORMAT_JSON":    1,
		"FORMAT_YAML":    2,
		"FORMAT_TOML":    3,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_linter_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_linter_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_linter_proto_rawDescGZIP(), []int{0}
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Format        Format                 `protobuf:"varint,2,opt,name=format,proto3,enum=configlinter.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_linter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_linter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CheckRequest) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNKNOWN
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_linter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_linter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type Issue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuleId         string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Severity       string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_linter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_linter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_linter_proto_rawDescGZIP(), []int{2}
}

func (x *Issue) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Issue) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

var File_linter_proto protoreflect.FileDescriptor

const file_linter_proto_rawDesc = "" +
	"\n" +
	"\flinter.proto\x12\fconfiglinter\"V\n" +
	"\fCheckRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12,\n" +
	"\x06format\x18\x02 \x01(\x0e2\x14.configlinter.FormatR\x06format\"<\n" +
	"\rCheckResponse\x12+\n" +
	"\x06issues\x18\x01 \x03(\v2\x13.configlinter.IssueR\x06issues\"\x92\x01\n" +
	"\x05Issue\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation*O\n" +
	"\x06Format\x12\x12\n" +
	"\x0eFORMAT_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vFORMAT_JSON\x10\x01\x12\x0f\n" +
	"\vFORMAT_YAML\x10\x02\x12\x0f\n" +
	"\vFORMAT_TOML\x10\x032V\n" +
	"\fConfigLinter\x12F\n" +
	"\vCheckConfig\x12\x1a.configlinter.CheckRequest\x1a\x1b.configlinter.CheckResponseB\x17Z\x15configlinter/proto/pbb\x06proto3"

var (
	file_linter_proto_rawDescOnce sync.Once
	file_linter_proto_rawDescData []byte
)

func file_linter_proto_rawDescGZIP() []byte {
	file_linter_proto_rawDescOnce.Do(func() {
		file_linter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_linter_proto_rawDesc), len(file_linter_proto_rawDesc)))
	})
	return file_linter_proto_rawDescData
}

var file_linter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_linter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_linter_proto_goTypes = []any{
	(Format)(0),           // 0: configlinter.Format
	(*CheckRequest)(nil),  // 1: configlinter.CheckRequest
	(*CheckResponse)(nil), // 2: configlinter.CheckResponse
	(*Issue)(nil),         // 3: configlinter.Issue
}
var file_linter_proto_depIdxs = []int32{
	0, // 0: configlinter.CheckRequest.format:type_name -> configlinter.Format
	3, // 1: configlinter.CheckResponse.issues:type_name -> configlinter.Issue
	1, // 2: configlinter.ConfigLinter.CheckConfig:input_type -> configlinter.CheckRequest
	2, // 3: configlinter.ConfigLinter.CheckConfig:output_type -> configlinter.CheckResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_linter_proto_init() }
func file_linter_proto_init() {
	if File_linter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_linter_proto_rawDesc), len(file_linter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linter_proto_goTypes,
		DependencyIndexes: file_linter_proto_depIdxs,
		EnumInfos:         file_linter_proto_enumTypes,
		MessageInfos:      file_linter_proto_msgTypes,
	}.Build()
	File_linter_proto = out.File
	file_linter_proto_goTypes = nil
	file_linter_proto_depIdxs = nil
}
