// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: proto/linter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigLinter_CheckConfig_FullMethodName = "/configlinter.ConfigLinter/CheckConfig"
)

// ConfigLinterClient is the client API for ConfigLinter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigLinterClient interface {
	CheckConfig(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type configLinterClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigLinterClient(cc grpc.ClientConnInterface) ConfigLinterClient {
	return &configLinterClient{cc}
}

func (c *configLinterClient) CheckConfig(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, ConfigLinter_CheckConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigLinterServer is the server API for ConfigLinter service.
// All implementations must embed UnimplementedConfigLinterServer
// for forward compatibility.
type ConfigLinterServer interface {
	CheckConfig(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedConfigLinterServer()
}

// UnimplementedConfigLinterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigLinterServer struct{}

func (UnimplementedConfigLinterServer) CheckConfig(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConfig not implemented")
}
func (UnimplementedConfigLinterServer) mustEmbedUnimplementedConfigLinterServer() {}
func (UnimplementedConfigLinterServer) testEmbeddedByValue()                      {}

// UnsafeConfigLinterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigLinterServer will
// result in compilation errors.
type UnsafeConfigLinterServer interface {
	mustEmbedUnimplementedConfigLinterServer()
}

func RegisterConfigLinterServer(s grpc.ServiceRegistrar, srv ConfigLinterServer) {
	// If the following call panics, it indicates UnimplementedConfigLinterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigLinter_ServiceDesc, srv)
}

func _ConfigLinter_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigLinterServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigLinter_CheckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigLinterServer).CheckConfig(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigLinter_ServiceDesc is the grpc.ServiceDesc for ConfigLinter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigLinter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configlinter.ConfigLinter",
	HandlerType: (*ConfigLinterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckConfig",
			Handler:    _ConfigLinter_CheckConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/linter.proto",
}
